version: '3.4'

services:
  sut:
    build: ./test
    volumes:
      - ./test:/tests-dir
    depends_on:
      - omnidb
    links:
      - omnidb
    command: python3 /tests-dir/test-omnidb.py

  omnidb:
    build: .
